### ISSUE TITLE
Return a plain text when we require a dataset which does not exist

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/collectory#150]
For example
https://collections-test.ala.org.au/ws/dataResource/dr16223_xxxxx

it returns 404 with plain text: no entity with uid = dr16223_xxxxx[], instead of a JSON

And I don't think the status should be 404

**Comment by adam-collins** [comment]
See also collections-test.ala.org.au/doesnotexist, it returns 404 because it does not exist with html content. 

The `dr` is a path variable so I think 404 is valid for a path that does not exist. The text content is unnecessary because that is what the status means, page does not exist.

I'll close this issue because
- 404 is accurate
- response content should be ignored so the format is irrelevant
