### ISSUE TITLE
Enforce country in data provider in GBIF

### ISSUE THREAD

**Issue by timrobertson100** [AtlasOfLivingAustralia/collectory#203]
Hi ALA'ers.

We notice several new/updated organisations in the GBIF registry come to us with no country set, which is a recurring problem. This affects the quarterly analytics in particular which provides reports of data published by institutions in the country and does get noticed.

I suggest a good addition would be to add a default country configuration (e.g. "AU" for the ALA.org.au installation) that is set if NULL before creating or updating the organisation in the GBIF registry somewhere around [here](https://github.com/AtlasOfLivingAustralia/collectory/blob/develop/grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy#L158) and [here](https://github.com/AtlasOfLivingAustralia/collectory/blob/develop/grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy#L125), or perhaps modify the collectory to make the field mandatory if that makes sense for the living atlas community.

Thank you

(CC @mattblissett @ahahn-gbif for info)

**Comment by djtfmartin** [comment]
thanks @MattBlissett  - i think its a good idea to enforce the country field on the GBIF side. Im not sure why these organisations have "lost" their country field, but i think we should make it mandatory on our side too.

Canterbury Museum is an outlier here. The associated country should be New Zealand.
It also looks like we have some duplication of "DEPARTMENT OF PLANNING AND ENVIRONMENT - Environment and Heritage"

cc @peggynewman

**Comment by peggynewman** [comment]
Thanks all. Yes Fenner school looks like a duplicate as well.

**Comment by adam-collins** [comment]
`gbifCountryToAttribute` is available on `Institution` and `DataProvider` entities. Changing this to mandatory. When creating or importing the default value is retrieved from the config `gbifDefaultEntityCountry`.

`gbifDefaultEntityCountry` must be set and is mandatory for application startup. 

When upgrading from an older version, `gbifCountryToAttribute` will be set to an empty string. This is added to the admin pages `dataProvider/list` and `institution/list` so that it can be easily identified and backfilled where required. 

`gbifCountryToAttribute` contains an ISO 3 digit country code. For `International`, `ZZZ` is used. This is converted to `ZZ` when sent to GBIF. See https://github.com/gbif/registry/issues/524

**Comment by adam-collins** [comment]
@djtfmartin @vjrj The result of adding a mandatory config property without a default has implications for https://github.com/AtlasOfLivingAustralia/ala-install. Any suggestions? Any preferred default?

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/collectory/pull/225
