### ISSUE TITLE
DwC terms and JSON map of parameters are being cleared during upload process

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/collectory#208]
We have recently identified a problem with Collectory when attempting to upload data. 

Upon clicking on the “Upload” button in the file upload section, it redirects us to the data uploading page, but it inadvertently erases the Darwin core terms that serve as the unique identifiers for a record. 

Similarly, within the Data Mobilisation section, various properties, including the JSON map of parameters, are being inadvertently cleared.

Is there a possible solution to preserve this information? as its alteration can lead to complications during data ingestion if it goes unnoticed.

raised by @cha801p

**Comment by adam-collins** [comment]
My understanding of this issue is that `Darwin core terms that uniquely identify a record` that appear when editing a data resource in the DataResource Edit -> Data Mobilisation -> Edit -> Connection Parameters section are not used as the defaults in the DataResource Edit -> File Upload -> Upload a data file page.

@cha801p Can I please get an example for the Data Mobilisation section JSON map of parameters getting cleared. I am unsure how to reproduce this.

**Comment by cha801p** [comment]
In the Protocol section of Data Mobilisation, when choosing the "Custom Webservice" option, if you switch to "Darwin Core Archive" and then return to "Custom Webservice," all the previously saved settings get reset.

**Comment by adam-collins** [comment]
Pull request https://github.com/AtlasOfLivingAustralia/collectory/pull/215

**Comment by adam-collins** [comment]
This is on collections test for testing

**Comment by kylie-m** [comment]
It's working well for me, based on my understanding of how it should function
